# Generated by Django 5.1.5 on 2025-02-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularlocation',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
